name: loong64
on:
  push:
    branches:
      - loong64-*
    tags:
      - release-loong64-*
  pull_request:
    branches:
      - loong64-*

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:13
    permissions:
      contents: read
    env:
      SECCOMP_VER: 2.6.0
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Print branch name
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "${{ github.base_ref }} (PR target)"
          else
            echo ${{ github.ref_name }}
          fi
      - name: Extract runc branch
        id: extract
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            REF=${{ github.base_ref }}
          else
            REF=${{ github.ref_name }}
          fi
          echo "REF=$REF"
          RAW_VERSION=$(echo $REF | awk -F'loong64-' '{print $2}')
          echo "RAW_VERSION=$RAW_VERSION"
          RUNC_BRANCH=$(echo $RAW_VERSION | awk -F'+' '{print $1}')
          echo "RUNC_BRANCH=$RUNC_BRANCH"
          echo "RUNC_BRANCH=$RUNC_BRANCH" >> ${GITHUB_ENV}
          if echo "$RAW_VERSION" | grep -qE '[+].*(alpha|beta|rc)'; then
            IS_STABLE=false
          else
            IS_STABLE=true
          fi
          echo "IS_STABLE=$IS_STABLE"
          echo "IS_STABLE=$IS_STABLE" >> ${GITHUB_OUTPUT}
      - name: Install build tools
        run: |
          apt update
          apt install -y git make golang file
      - name: Install loong64 cross-compiler
        run: |
          apt update
          apt install -y gcc-loongarch64-linux-gnu binutils-loongarch64-linux-gnu libc-dev-loong64-cross
      - name: Install libseccomp for loong64
        run: |
          apt update
          apt install -y wget gperf
          wget -q https://github.com/seccomp/libseccomp/releases/download/v${{ env.SECCOMP_VER }}/libseccomp-${{ env.SECCOMP_VER }}.tar.gz
          tar xf libseccomp-${{ env.SECCOMP_VER }}.tar.gz
          cd libseccomp-${{ env.SECCOMP_VER }}
          ./configure --host=loongarch64-linux-gnu --prefix=/usr/local/loong64
          make -j$(nproc)
          make install
      - name: Clone runc
        run:
          git clone --branch ${{ env.RUNC_BRANCH }} --depth 1 https://github.com/opencontainers/runc.git runc
      - name: ls
        run: ls -lah
      #- name: Apply patches
      #  working-directory: runc
      #  run: git apply ../*.patch
      - name: Build runc
        working-directory: runc
        run: PKG_CONFIG_PATH=/usr/local/loong64/lib/pkgconfig make GOARCH=loong64 CC=loongarch64-linux-gnu-gcc static
      - name: Print binary SHA-256 checksums
        working-directory: runc
        run: |
          find runc -type f | xargs sha256sum
      - name: Inspect binary file types
        working-directory: runc
        run: |
          echo "=== bin ==="
          file runc
      - name: Upload binaries
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: runc-loong64-binaries
          path: |
            runc/runc

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download binaries
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          name: runc-loong64-binaries
          path: loong64-artifacts
      - name: Create Release
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          name: ${{ github.ref_name }}
          prerelease: ${{ env.IS_STABLE == 'false' }}
          make_latest: ${{ env.IS_STABLE == 'true' && 'legacy' || 'false' }}
          files: |
            loong64-artifacts/**
