name: loong64
on:
  push:
    branches:
      - loong64-*
    tags:
      - release-loong64-*
  pull_request:
    branches:
      - loong64-*

jobs:
  build:
    runs-on: ubuntu-latest
    container: debian:13
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Print branch name
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "${{ github.base_ref }} (PR target)"
          else
            echo ${{ github.ref_name }}
          fi
      - name: Extract runc branch
        id: extract
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            REF=${{ github.base_ref }}
          else
            REF=${{ github.ref_name }}
          fi
          echo "REF=$REF"
          RAW_VERSION=$(echo $REF | awk -F'loong64-' '{print $2}')
          echo "RAW_VERSION=$RAW_VERSION"
          RUNC_BRANCH=$(echo $RAW_VERSION | awk -F'+' '{print $1}')
          echo "RUNC_BRANCH=$RUNC_BRANCH"
          echo "RUNC_BRANCH=$RUNC_BRANCH" >> ${GITHUB_ENV}
          if echo "$RAW_VERSION" | grep -qE '[+].*(alpha|beta|rc)'; then
            IS_STABLE=false
          else
            IS_STABLE=true
          fi
          echo "IS_STABLE=$IS_STABLE"
          echo "IS_STABLE=$IS_STABLE" >> ${GITHUB_OUTPUT}
      - name: Install build tools
        run: |
          apt update
          apt install -y git make golang file libseccomp-dev pkg-config gcc-loongarch64-linux-gnu binutils-loongarch64-linux-gnu
      - name: Clone runc
        run:
          git clone --branch ${{ env.RUNC_BRANCH }} --depth 1 https://github.com/opencontainers/runc.git runc
      - name: ls
        run: ls -lah
      #- name: Apply patches
      #  working-directory: runc
      #  run: git apply ../*.patch
      - name: Build runc
        working-directory: runc
        env:
          GOOS: linux
          GOARCH: loong64
          CC: loongarch64-linux-gnu-gcc
          CGO_ENABLED: 0
        run: make RUNC_BUILDTAGS="-seccomp"
      - name: Print binary SHA-256 checksums
        working-directory: runc
        run: |
          find runc -type f | xargs sha256sum
      - name: Inspect binary file types
        working-directory: runc
        run: |
          echo "=== bin ==="
          file runc
      - name: Upload binaries
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: runc-loong64-binaries
          path: |
            runc/runc
